### ISSUE TITLE
Current level pointer broke on some computers

### ISSUE THREAD

**Issue by Happyrobot33** [Happyrobot33/Autosplitters#9]
The level pointer on some computers is 0. refine the pinter search some more

**Comment by Happyrobot33** [comment]
possible fix in https://github.com/Happyrobot33/Autosplitters/commit/338d75af0022fc6fd529e8b2a61ef7f838533f38 waiting for testing to confirm fix

**Comment by AJ213** [comment]
Was caused by the user's eye-tracker program. This can be fixed, but only by people who have the program. Fixing this issue should be considered a feature since really it is about supporting a specific eye-tracking program. It might be possible to find better pointers that work on computers despite them having an eye tracker program, but this can be a difficult process.

**Comment by Happyrobot33** [comment]
Somewhat fixed. will reopen if another computer with the same issue is found
